{
  "language": "java",
  "jdk": "oraclejdk9",
  "install": "ant build",
  "after_success": [
    "python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

